name: Deploy Static Site to S3 via OIDC

on:
  push:
    branches:
      - main # mainブランチへのプッシュ時にワークフローを実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    # GitHub ActionsにOIDCトークンを発行し、リポジトリを読み取る権限を付与
    permissions:
      id-token: write # OIDCトークンをリクエストするために必須
      contents: read  # リポジトリのコードをチェックアウトするために必須

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # 作成したIAMロールのARNを指定
          role-to-assume: arn:aws:iam::252170044718:role/GitHubActionsRole-0603game-S3Sync
          aws-region: ap-northeast-1
          # (オプション) セッションに名前を付けるとCloudTrailログで識別しやすくなります
          role-session-name: GitHubActionsS3DeploySession 

      - name: Sync files to S3
        run: |
          aws s3 sync ./ s3://tano-0603game-bucket/ --exclude ".git/*" --exclude ".github/*" --exclude "README.md" --exclude "CLAUDE.md" --exclude "*.code-workspace" --exclude "test-local.html" --delete
